---
version: '2.1'
services:

  #CLUSTER 1
  zookeeper-europe:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper-europe
    container_name: zookeeper-europe
    ports:
      - "2180:2180"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2180
      ZOOKEEPER_TICK_TIME: 2000

  broker-europe:
    image: confluentinc/cp-server:7.0.0
    hostname: broker-europe
    container_name: broker-europe
    depends_on:
      - zookeeper-europe
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-europe:2180'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-europe:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-europe:29094
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  broker-ui-europe:
    image: provectuslabs/kafka-ui:latest
    hostname: broker-ui-europe
    container_name: broker-ui-europe
    ports:
      - 9080:9080
    depends_on:
      - broker-europe
    environment:
      - SERVER_PORT=9080
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker-europe:29094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-europe:2180
      - KAFKA_CLUSTERS_0_NAME=local


  #CLUSTER 2      
  zookeeper-north-america:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper-north-america
    container_name: zookeeper-north-america
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker-north-america:
    image: confluentinc/cp-server:7.0.0
    hostname: broker-north-america
    container_name: broker-north-america
    depends_on:
      - zookeeper-north-america
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-north-america:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-north-america:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry-north-america:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-north-america:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  schema-registry-north-america:
    image: confluentinc/cp-schema-registry:7.0.0
    hostname: schema-registry-north-america
    container_name: schema-registry-north-america
    depends_on:
      - broker-north-america
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-north-america
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker-north-america:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  connect-north-america:
    image: cnfldemos/cp-server-connect-datagen:0.5.0-6.2.0
    hostname: connect-north-america
    container_name: connect-north-america
    depends_on:
      - broker-north-america
      - schema-registry-north-america
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker-north-america:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-north-america
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry-north-america:8081
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry-north-america:8081
      # CLASSPATH required due to CC-2422
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.0.0.jar
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR

  broker-ui-north-america:
    image: provectuslabs/kafka-ui:latest
    hostname: broker-ui-north-america
    container_name: broker-ui-north-america
    ports:
      - 9081:9081
    depends_on:
      - broker-north-america
    environment:
      - SERVER_PORT=9081
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker-north-america:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-north-america:2181
      - KAFKA_CLUSTERS_0_NAME=local

  # OTHER
  datagen-europe:
    image: datagen-europe
    hostname: datagen-europe
    container_name: datagen-europe
    depends_on:
      - broker-europe
    environment:
      - KAFKA_HOST=broker-europe:29094
      - KAFKA_TOPIC=europe.topic.masterdata  
